/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Home (void)
{
  GtkWidget *Home;
  GtkWidget *Fixed;
  GtkWidget *ggenetryUser;
  GtkWidget *ggentryPass;
  GtkWidget *labelwrong;
  GtkWidget *image18;
  GtkWidget *ggbuttonLogin;
  GtkWidget *ggbuttonIinscription;
  GtkWidget *ggbuttonVisiteur;

  Home = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Home), _("Home"));

  Fixed = gtk_fixed_new ();
  gtk_widget_show (Fixed);
  gtk_container_add (GTK_CONTAINER (Home), Fixed);

  ggenetryUser = gtk_entry_new ();
  gtk_widget_show (ggenetryUser);
  gtk_fixed_put (GTK_FIXED (Fixed), ggenetryUser, 464, 272);
  gtk_widget_set_size_request (ggenetryUser, 224, 42);
  gtk_entry_set_invisible_char (GTK_ENTRY (ggenetryUser), 8226);

  ggentryPass = gtk_entry_new ();
  gtk_widget_show (ggentryPass);
  gtk_fixed_put (GTK_FIXED (Fixed), ggentryPass, 464, 432);
  gtk_widget_set_size_request (ggentryPass, 224, 40);
  gtk_entry_set_visibility (GTK_ENTRY (ggentryPass), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (ggentryPass), 8226);

  labelwrong = gtk_label_new ("");
  gtk_widget_show (labelwrong);
  gtk_fixed_put (GTK_FIXED (Fixed), labelwrong, 144, 32);
  gtk_widget_set_size_request (labelwrong, 328, 56);

  image18 = create_pixmap (Home, "WELCOME.jpg");
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (Fixed), image18, 0, 0);
  gtk_widget_set_size_request (image18, 1000, 712);

  ggbuttonLogin = gtk_button_new_with_mnemonic (_("Login"));
  gtk_widget_show (ggbuttonLogin);
  gtk_fixed_put (GTK_FIXED (Fixed), ggbuttonLogin, 768, 616);
  gtk_widget_set_size_request (ggbuttonLogin, 144, 49);

  ggbuttonIinscription = gtk_button_new_with_mnemonic (_("Inscrivez-Vous"));
  gtk_widget_show (ggbuttonIinscription);
  gtk_fixed_put (GTK_FIXED (Fixed), ggbuttonIinscription, 432, 616);
  gtk_widget_set_size_request (ggbuttonIinscription, 144, 49);

  ggbuttonVisiteur = gtk_button_new_with_mnemonic (_("Mode Visiteur"));
  gtk_widget_show (ggbuttonVisiteur);
  gtk_fixed_put (GTK_FIXED (Fixed), ggbuttonVisiteur, 104, 616);
  gtk_widget_set_size_request (ggbuttonVisiteur, 144, 49);

  g_signal_connect ((gpointer) ggbuttonLogin, "clicked",
                    G_CALLBACK (on_ggbuttonLogin_clicked),
                    NULL);
  g_signal_connect ((gpointer) ggbuttonIinscription, "clicked",
                    G_CALLBACK (on_ggbuttonIinscription_clicked),
                    NULL);
  g_signal_connect ((gpointer) ggbuttonVisiteur, "clicked",
                    G_CALLBACK (on_ggbuttonVisiteur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Home, Home, "Home");
  GLADE_HOOKUP_OBJECT (Home, Fixed, "Fixed");
  GLADE_HOOKUP_OBJECT (Home, ggenetryUser, "ggenetryUser");
  GLADE_HOOKUP_OBJECT (Home, ggentryPass, "ggentryPass");
  GLADE_HOOKUP_OBJECT (Home, labelwrong, "labelwrong");
  GLADE_HOOKUP_OBJECT (Home, image18, "image18");
  GLADE_HOOKUP_OBJECT (Home, ggbuttonLogin, "ggbuttonLogin");
  GLADE_HOOKUP_OBJECT (Home, ggbuttonIinscription, "ggbuttonIinscription");
  GLADE_HOOKUP_OBJECT (Home, ggbuttonVisiteur, "ggbuttonVisiteur");

  return Home;
}

GtkWidget*
create_ModeVisiteur (void)
{
  GtkWidget *ModeVisiteur;
  GtkWidget *fixed11;
  GtkWidget *image31;
  GtkWidget *buttonConnect;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *buttonInscriV;

  ModeVisiteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ModeVisiteur), _("Mode Visiteur"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (ModeVisiteur), fixed11);

  image31 = create_pixmap (ModeVisiteur, "visiteur.jpg");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed11), image31, 0, 0);
  gtk_widget_set_size_request (image31, 800, 600);
  gtk_misc_set_alignment (GTK_MISC (image31), 0.11, 0.64);

  buttonConnect = gtk_button_new_with_mnemonic (_("Connecter"));
  gtk_widget_show (buttonConnect);
  gtk_fixed_put (GTK_FIXED (fixed11), buttonConnect, 624, 120);
  gtk_widget_set_size_request (buttonConnect, 136, 41);

  label27 = gtk_label_new (_("Bienvenue ! Vous pouvez consulter\n                                                                 tout nos offres !"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed11), label27, 128, 104);
  gtk_widget_set_size_request (label27, 408, 48);

  label28 = gtk_label_new (_("Pour faire des r\303\251servations  il suffit de vous connecter !\n                                                      Si vous n'avez pas de compte inscrivez vous"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed11), label28, 64, 520);
  gtk_widget_set_size_request (label28, 520, 64);

  buttonInscriV = gtk_button_new_with_mnemonic (_("Inscrivez-Vous"));
  gtk_widget_show (buttonInscriV);
  gtk_fixed_put (GTK_FIXED (fixed11), buttonInscriV, 608, 536);
  gtk_widget_set_size_request (buttonInscriV, 136, 40);

  g_signal_connect ((gpointer) buttonConnect, "clicked",
                    G_CALLBACK (on_buttonConnect_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonInscriV, "clicked",
                    G_CALLBACK (on_buttonInscriV_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ModeVisiteur, ModeVisiteur, "ModeVisiteur");
  GLADE_HOOKUP_OBJECT (ModeVisiteur, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (ModeVisiteur, image31, "image31");
  GLADE_HOOKUP_OBJECT (ModeVisiteur, buttonConnect, "buttonConnect");
  GLADE_HOOKUP_OBJECT (ModeVisiteur, label27, "label27");
  GLADE_HOOKUP_OBJECT (ModeVisiteur, label28, "label28");
  GLADE_HOOKUP_OBJECT (ModeVisiteur, buttonInscriV, "buttonInscriV");

  return ModeVisiteur;
}

GtkWidget*
create_ModeAdmin (void)
{
  GtkWidget *ModeAdmin;
  GtkWidget *fixed3;
  GtkWidget *image19;
  GtkWidget *label3;
  GtkWidget *buttonDecoA;
  GtkWidget *buttonAGE;
  GtkWidget *button14;
  GtkWidget *button15;
  GtkWidget *buttonAGC;

  ModeAdmin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ModeAdmin), _("Mode Administrateur"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (ModeAdmin), fixed3);

  image19 = create_pixmap (ModeAdmin, "admin.jpg");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed3), image19, 0, 0);
  gtk_widget_set_size_request (image19, 1080, 808);

  label3 = gtk_label_new (_("Bonjour Admin , "));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed3), label3, 352, 128);
  gtk_widget_set_size_request (label3, 176, 56);

  buttonDecoA = gtk_button_new_with_mnemonic (_("Se d\303\251conecter"));
  gtk_widget_show (buttonDecoA);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonDecoA, 0, 756);
  gtk_widget_set_size_request (buttonDecoA, 196, 51);

  buttonAGE = gtk_button_new_with_mnemonic (_("G.Employ\303\251s"));
  gtk_widget_show (buttonAGE);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonAGE, 328, 600);
  gtk_widget_set_size_request (buttonAGE, 144, 49);

  button14 = gtk_button_new_with_mnemonic ("");
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed3), button14, 600, 600);
  gtk_widget_set_size_request (button14, 144, 49);

  button15 = gtk_button_new_with_mnemonic ("");
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed3), button15, 840, 600);
  gtk_widget_set_size_request (button15, 144, 49);

  buttonAGC = gtk_button_new_with_mnemonic (_("G.Clients"));
  gtk_widget_show (buttonAGC);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonAGC, 88, 600);
  gtk_widget_set_size_request (buttonAGC, 144, 49);

  g_signal_connect ((gpointer) buttonDecoA, "clicked",
                    G_CALLBACK (on_buttonDecoA_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAGE, "clicked",
                    G_CALLBACK (on_buttonAGE_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAGC, "clicked",
                    G_CALLBACK (on_buttonAGC_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ModeAdmin, ModeAdmin, "ModeAdmin");
  GLADE_HOOKUP_OBJECT (ModeAdmin, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (ModeAdmin, image19, "image19");
  GLADE_HOOKUP_OBJECT (ModeAdmin, label3, "label3");
  GLADE_HOOKUP_OBJECT (ModeAdmin, buttonDecoA, "buttonDecoA");
  GLADE_HOOKUP_OBJECT (ModeAdmin, buttonAGE, "buttonAGE");
  GLADE_HOOKUP_OBJECT (ModeAdmin, button14, "button14");
  GLADE_HOOKUP_OBJECT (ModeAdmin, button15, "button15");
  GLADE_HOOKUP_OBJECT (ModeAdmin, buttonAGC, "buttonAGC");

  return ModeAdmin;
}

GtkWidget*
create_GestionAClient (void)
{
  GtkWidget *GestionAClient;
  GtkWidget *fixed4;
  GtkWidget *entryRechercherAC;
  GtkWidget *treeviewAclient;
  GtkWidget *image32;
  GtkWidget *label7;
  GtkWidget *buttonACModifier;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label30;
  GtkWidget *buttonACSupprimer;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label29;
  GtkWidget *buttonACretour;
  GtkWidget *image1;

  GestionAClient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GestionAClient), _("Gestion  des Clients"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (GestionAClient), fixed4);

  entryRechercherAC = gtk_entry_new ();
  gtk_widget_show (entryRechercherAC);
  gtk_fixed_put (GTK_FIXED (fixed4), entryRechercherAC, 960, 64);
  gtk_widget_set_size_request (entryRechercherAC, 168, 34);
  gtk_entry_set_text (GTK_ENTRY (entryRechercherAC), _("Rechercher....."));
  gtk_entry_set_invisible_char (GTK_ENTRY (entryRechercherAC), 8226);

  treeviewAclient = gtk_tree_view_new ();
  gtk_widget_show (treeviewAclient);
  gtk_fixed_put (GTK_FIXED (fixed4), treeviewAclient, 112, 232);
  gtk_widget_set_size_request (treeviewAclient, 944, 392);

  image32 = create_pixmap (GestionAClient, "gclient.jpg");
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed4), image32, 0, 0);
  gtk_widget_set_size_request (image32, 1170, 850);

  label7 = gtk_label_new (_("Recherche :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed4), label7, 856, 64);
  gtk_widget_set_size_request (label7, 104, 32);

  buttonACModifier = gtk_button_new ();
  gtk_widget_show (buttonACModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonACModifier, 896, 656);
  gtk_widget_set_size_request (buttonACModifier, 144, 49);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonACModifier), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox2), label30, FALSE, FALSE, 0);

  buttonACSupprimer = gtk_button_new ();
  gtk_widget_show (buttonACSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonACSupprimer, 720, 656);
  gtk_widget_set_size_request (buttonACSupprimer, 144, 49);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonACSupprimer), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox1), label29, FALSE, FALSE, 0);

  buttonACretour = gtk_button_new ();
  gtk_widget_show (buttonACretour);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonACretour, 96, 120);
  gtk_widget_set_size_request (buttonACretour, 120, 48);

  image1 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (buttonACretour), image1);

  g_signal_connect ((gpointer) buttonACretour, "clicked",
                    G_CALLBACK (on_buttonACretour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GestionAClient, GestionAClient, "GestionAClient");
  GLADE_HOOKUP_OBJECT (GestionAClient, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (GestionAClient, entryRechercherAC, "entryRechercherAC");
  GLADE_HOOKUP_OBJECT (GestionAClient, treeviewAclient, "treeviewAclient");
  GLADE_HOOKUP_OBJECT (GestionAClient, image32, "image32");
  GLADE_HOOKUP_OBJECT (GestionAClient, label7, "label7");
  GLADE_HOOKUP_OBJECT (GestionAClient, buttonACModifier, "buttonACModifier");
  GLADE_HOOKUP_OBJECT (GestionAClient, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (GestionAClient, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (GestionAClient, image3, "image3");
  GLADE_HOOKUP_OBJECT (GestionAClient, label30, "label30");
  GLADE_HOOKUP_OBJECT (GestionAClient, buttonACSupprimer, "buttonACSupprimer");
  GLADE_HOOKUP_OBJECT (GestionAClient, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (GestionAClient, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (GestionAClient, image2, "image2");
  GLADE_HOOKUP_OBJECT (GestionAClient, label29, "label29");
  GLADE_HOOKUP_OBJECT (GestionAClient, buttonACretour, "buttonACretour");
  GLADE_HOOKUP_OBJECT (GestionAClient, image1, "image1");

  return GestionAClient;
}

GtkWidget*
create_GestionAEmployes (void)
{
  GtkWidget *GestionAEmployes;
  GtkWidget *fixed5;
  GtkWidget *entry1;
  GtkWidget *treeviewemp;
  GtkWidget *image33;
  GtkWidget *label31;
  GtkWidget *button23;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image6;
  GtkWidget *label33;
  GtkWidget *button22;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image5;
  GtkWidget *label32;
  GtkWidget *buttonEAretour;
  GtkWidget *image4;
  GtkWidget *buttonAEMajouter;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image7;
  GtkWidget *label53;

  GestionAEmployes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GestionAEmployes), _("Gestion des Employ\303\251s"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (GestionAEmployes), fixed5);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed5), entry1, 976, 56);
  gtk_widget_set_size_request (entry1, 168, 34);
  gtk_entry_set_text (GTK_ENTRY (entry1), _("Rechercher....."));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  treeviewemp = gtk_tree_view_new ();
  gtk_widget_show (treeviewemp);
  gtk_fixed_put (GTK_FIXED (fixed5), treeviewemp, 104, 240);
  gtk_widget_set_size_request (treeviewemp, 944, 392);

  image33 = create_pixmap (GestionAEmployes, "gemp.jpg");
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed5), image33, 0, 0);
  gtk_widget_set_size_request (image33, 1165, 853);

  label31 = gtk_label_new (_("Recherche :"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 856, 56);
  gtk_widget_set_size_request (label31, 120, 32);

  button23 = gtk_button_new ();
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed5), button23, 712, 672);
  gtk_widget_set_size_request (button23, 144, 49);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button23), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox4), image6, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox4), label33, FALSE, FALSE, 0);

  button22 = gtk_button_new ();
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed5), button22, 544, 672);
  gtk_widget_set_size_request (button22, 144, 49);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button22), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox3), image5, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox3), label32, FALSE, FALSE, 0);

  buttonEAretour = gtk_button_new ();
  gtk_widget_show (buttonEAretour);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonEAretour, 96, 120);
  gtk_widget_set_size_request (buttonEAretour, 120, 48);

  image4 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (buttonEAretour), image4);

  buttonAEMajouter = gtk_button_new ();
  gtk_widget_show (buttonAEMajouter);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonAEMajouter, 880, 672);
  gtk_widget_set_size_request (buttonAEMajouter, 144, 49);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonAEMajouter), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox5), label53, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonEAretour, "clicked",
                    G_CALLBACK (on_buttonEAretour_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAEMajouter, "clicked",
                    G_CALLBACK (on_buttonAEMajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GestionAEmployes, GestionAEmployes, "GestionAEmployes");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, treeviewemp, "treeviewemp");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, image33, "image33");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, label31, "label31");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, button23, "button23");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, image6, "image6");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, label33, "label33");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, button22, "button22");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, image5, "image5");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, label32, "label32");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, buttonEAretour, "buttonEAretour");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, image4, "image4");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, buttonAEMajouter, "buttonAEMajouter");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, image7, "image7");
  GLADE_HOOKUP_OBJECT (GestionAEmployes, label53, "label53");

  return GestionAEmployes;
}

GtkWidget*
create_ModeEmploye (void)
{
  GtkWidget *ModeEmploye;
  GtkWidget *fixed6;
  GtkWidget *image20;
  GtkWidget *label24;
  GtkWidget *buttonEGC;
  GtkWidget *buttonEGFactures;
  GtkWidget *button12;
  GtkWidget *button11;
  GtkWidget *image8;
  GtkWidget *buttonDecoEmp;
  GtkWidget *buttonEPrestations;

  ModeEmploye = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ModeEmploye), _("Mode Employ\303\251"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (ModeEmploye), fixed6);

  image20 = create_pixmap (ModeEmploye, "emp.jpg");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed6), image20, 0, 0);
  gtk_widget_set_size_request (image20, 1080, 808);

  label24 = gtk_label_new (_("Bienveunue Ch\303\250r(e) Employ\303\251(e) ,"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed6), label24, 328, 120);
  gtk_widget_set_size_request (label24, 288, 72);

  buttonEGC = gtk_button_new_with_mnemonic (_("G.Clients"));
  gtk_widget_show (buttonEGC);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonEGC, 72, 536);
  gtk_widget_set_size_request (buttonEGC, 144, 49);

  buttonEGFactures = gtk_button_new_with_mnemonic (_("Factures"));
  gtk_widget_show (buttonEGFactures);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonEGFactures, 272, 536);
  gtk_widget_set_size_request (buttonEGFactures, 144, 49);

  button12 = gtk_button_new_with_mnemonic ("");
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed6), button12, 648, 536);
  gtk_widget_set_size_request (button12, 144, 49);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed6), button11, 840, 536);
  gtk_widget_set_size_request (button11, 144, 49);

  image8 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_container_add (GTK_CONTAINER (button11), image8);

  buttonDecoEmp = gtk_button_new_with_mnemonic (_("Se d\303\251conecter"));
  gtk_widget_show (buttonDecoEmp);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonDecoEmp, 0, 756);
  gtk_widget_set_size_request (buttonDecoEmp, 196, 51);

  buttonEPrestations = gtk_button_new_with_mnemonic (_("Prestations"));
  gtk_widget_show (buttonEPrestations);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonEPrestations, 464, 536);
  gtk_widget_set_size_request (buttonEPrestations, 144, 49);

  g_signal_connect ((gpointer) buttonEGC, "clicked",
                    G_CALLBACK (on_buttonEGC_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonEGFactures, "clicked",
                    G_CALLBACK (on_buttonEGFactures_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonDecoEmp, "clicked",
                    G_CALLBACK (on_buttonDecoEmp_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonEPrestations, "clicked",
                    G_CALLBACK (on_buttonEPrestations_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ModeEmploye, ModeEmploye, "ModeEmploye");
  GLADE_HOOKUP_OBJECT (ModeEmploye, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (ModeEmploye, image20, "image20");
  GLADE_HOOKUP_OBJECT (ModeEmploye, label24, "label24");
  GLADE_HOOKUP_OBJECT (ModeEmploye, buttonEGC, "buttonEGC");
  GLADE_HOOKUP_OBJECT (ModeEmploye, buttonEGFactures, "buttonEGFactures");
  GLADE_HOOKUP_OBJECT (ModeEmploye, button12, "button12");
  GLADE_HOOKUP_OBJECT (ModeEmploye, button11, "button11");
  GLADE_HOOKUP_OBJECT (ModeEmploye, image8, "image8");
  GLADE_HOOKUP_OBJECT (ModeEmploye, buttonDecoEmp, "buttonDecoEmp");
  GLADE_HOOKUP_OBJECT (ModeEmploye, buttonEPrestations, "buttonEPrestations");

  return ModeEmploye;
}

GtkWidget*
create_GestionEClient (void)
{
  GtkWidget *GestionEClient;
  GtkWidget *fixed7;
  GtkWidget *entry2;
  GtkWidget *treeviewEclient;
  GtkWidget *image34;
  GtkWidget *label54;
  GtkWidget *button27;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image11;
  GtkWidget *label56;
  GtkWidget *button26;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image10;
  GtkWidget *label55;
  GtkWidget *buttonretourCE;
  GtkWidget *image9;

  GestionEClient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GestionEClient), _("Gestion des Clients"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (GestionEClient), fixed7);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed7), entry2, 968, 64);
  gtk_widget_set_size_request (entry2, 168, 34);
  gtk_entry_set_text (GTK_ENTRY (entry2), _("Rechercher....."));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  treeviewEclient = gtk_tree_view_new ();
  gtk_widget_show (treeviewEclient);
  gtk_fixed_put (GTK_FIXED (fixed7), treeviewEclient, 120, 240);
  gtk_widget_set_size_request (treeviewEclient, 944, 392);

  image34 = create_pixmap (GestionEClient, "gclient.jpg");
  gtk_widget_show (image34);
  gtk_fixed_put (GTK_FIXED (fixed7), image34, 0, 0);
  gtk_widget_set_size_request (image34, 1184, 856);

  label54 = gtk_label_new (_("Recherche :"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed7), label54, 848, 64);
  gtk_widget_set_size_request (label54, 120, 32);

  button27 = gtk_button_new ();
  gtk_widget_show (button27);
  gtk_fixed_put (GTK_FIXED (fixed7), button27, 888, 672);
  gtk_widget_set_size_request (button27, 144, 48);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button27), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image11 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox7), image11, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox7), label56, FALSE, FALSE, 0);

  button26 = gtk_button_new ();
  gtk_widget_show (button26);
  gtk_fixed_put (GTK_FIXED (fixed7), button26, 712, 672);
  gtk_widget_set_size_request (button26, 144, 48);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button26), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox6), image10, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox6), label55, FALSE, FALSE, 0);

  buttonretourCE = gtk_button_new ();
  gtk_widget_show (buttonretourCE);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonretourCE, 104, 120);
  gtk_widget_set_size_request (buttonretourCE, 120, 48);

  image9 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_container_add (GTK_CONTAINER (buttonretourCE), image9);

  g_signal_connect ((gpointer) buttonretourCE, "clicked",
                    G_CALLBACK (on_buttonretourCE_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GestionEClient, GestionEClient, "GestionEClient");
  GLADE_HOOKUP_OBJECT (GestionEClient, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (GestionEClient, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (GestionEClient, treeviewEclient, "treeviewEclient");
  GLADE_HOOKUP_OBJECT (GestionEClient, image34, "image34");
  GLADE_HOOKUP_OBJECT (GestionEClient, label54, "label54");
  GLADE_HOOKUP_OBJECT (GestionEClient, button27, "button27");
  GLADE_HOOKUP_OBJECT (GestionEClient, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (GestionEClient, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (GestionEClient, image11, "image11");
  GLADE_HOOKUP_OBJECT (GestionEClient, label56, "label56");
  GLADE_HOOKUP_OBJECT (GestionEClient, button26, "button26");
  GLADE_HOOKUP_OBJECT (GestionEClient, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (GestionEClient, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (GestionEClient, image10, "image10");
  GLADE_HOOKUP_OBJECT (GestionEClient, label55, "label55");
  GLADE_HOOKUP_OBJECT (GestionEClient, buttonretourCE, "buttonretourCE");
  GLADE_HOOKUP_OBJECT (GestionEClient, image9, "image9");

  return GestionEClient;
}

GtkWidget*
create_Prestations (void)
{
  GtkWidget *Prestations;
  GtkWidget *fixed8;
  GtkWidget *image35;
  GtkWidget *buttonEvols;
  GtkWidget *buttonELocation;
  GtkWidget *buttonEHyber;
  GtkWidget *buttonretourPE;
  GtkWidget *image12;

  Prestations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Prestations), _("Prestations"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (Prestations), fixed8);

  image35 = create_pixmap (Prestations, "pres.jpg");
  gtk_widget_show (image35);
  gtk_fixed_put (GTK_FIXED (fixed8), image35, 0, 0);
  gtk_widget_set_size_request (image35, 813, 619);
  gtk_misc_set_alignment (GTK_MISC (image35), 0.14, 0.63);

  buttonEvols = gtk_button_new_with_mnemonic (_("Vols"));
  gtk_widget_show (buttonEvols);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonEvols, 143, 464);
  gtk_widget_set_size_request (buttonEvols, 144, 48);

  buttonELocation = gtk_button_new_with_mnemonic (_("Location"));
  gtk_widget_show (buttonELocation);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonELocation, 352, 464);
  gtk_widget_set_size_request (buttonELocation, 144, 48);

  buttonEHyber = gtk_button_new_with_mnemonic (_("Hybergement"));
  gtk_widget_show (buttonEHyber);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonEHyber, 552, 464);
  gtk_widget_set_size_request (buttonEHyber, 144, 48);

  buttonretourPE = gtk_button_new ();
  gtk_widget_show (buttonretourPE);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonretourPE, 136, 128);
  gtk_widget_set_size_request (buttonretourPE, 103, 44);

  image12 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_container_add (GTK_CONTAINER (buttonretourPE), image12);

  g_signal_connect ((gpointer) buttonEvols, "clicked",
                    G_CALLBACK (on_buttonEvols_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonELocation, "clicked",
                    G_CALLBACK (on_buttonELocation_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonEHyber, "clicked",
                    G_CALLBACK (on_buttonEHyber_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourPE, "clicked",
                    G_CALLBACK (on_buttonretourPE_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Prestations, Prestations, "Prestations");
  GLADE_HOOKUP_OBJECT (Prestations, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (Prestations, image35, "image35");
  GLADE_HOOKUP_OBJECT (Prestations, buttonEvols, "buttonEvols");
  GLADE_HOOKUP_OBJECT (Prestations, buttonELocation, "buttonELocation");
  GLADE_HOOKUP_OBJECT (Prestations, buttonEHyber, "buttonEHyber");
  GLADE_HOOKUP_OBJECT (Prestations, buttonretourPE, "buttonretourPE");
  GLADE_HOOKUP_OBJECT (Prestations, image12, "image12");

  return Prestations;
}

GtkWidget*
create_Factures (void)
{
  GtkWidget *Factures;
  GtkWidget *fixed9;
  GtkWidget *buttonretourFE;
  GtkWidget *image13;

  Factures = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Factures), _("Factures"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (Factures), fixed9);

  buttonretourFE = gtk_button_new ();
  gtk_widget_show (buttonretourFE);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonretourFE, 8, 8);
  gtk_widget_set_size_request (buttonretourFE, 88, 32);

  image13 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_container_add (GTK_CONTAINER (buttonretourFE), image13);

  g_signal_connect ((gpointer) buttonretourFE, "clicked",
                    G_CALLBACK (on_buttonretourFE_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Factures, Factures, "Factures");
  GLADE_HOOKUP_OBJECT (Factures, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (Factures, buttonretourFE, "buttonretourFE");
  GLADE_HOOKUP_OBJECT (Factures, image13, "image13");

  return Factures;
}

GtkWidget*
create_ModeClient (void)
{
  GtkWidget *ModeClient;
  GtkWidget *fixed10;
  GtkWidget *image21;
  GtkWidget *label26;
  GtkWidget *buttondecoclient;
  GtkWidget *buttonCVols;
  GtkWidget *buttonPanier;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image30;
  GtkWidget *label95;
  GtkWidget *buttonCLocation;
  GtkWidget *buttonCHyber;

  ModeClient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ModeClient), _("Mode Clients"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (ModeClient), fixed10);

  image21 = create_pixmap (ModeClient, "client.jpg");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed10), image21, 0, 0);
  gtk_widget_set_size_request (image21, 1080, 808);

  label26 = gtk_label_new (_("Bienveunue Ch\303\250r(e) Client(e) , \n                                                      \303\240 Votre Service"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed10), label26, 352, 128);
  gtk_widget_set_size_request (label26, 288, 72);

  buttondecoclient = gtk_button_new_with_mnemonic (_("Se d\303\251conecter"));
  gtk_widget_show (buttondecoclient);
  gtk_fixed_put (GTK_FIXED (fixed10), buttondecoclient, 0, 755);
  gtk_widget_set_size_request (buttondecoclient, 196, 51);

  buttonCVols = gtk_button_new_with_mnemonic (_("Vols"));
  gtk_widget_show (buttonCVols);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonCVols, 216, 616);
  gtk_widget_set_size_request (buttonCVols, 144, 49);

  buttonPanier = gtk_button_new ();
  gtk_widget_show (buttonPanier);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonPanier, 888, 56);
  gtk_widget_set_size_request (buttonPanier, 144, 48);
  gtk_button_set_relief (GTK_BUTTON (buttonPanier), GTK_RELIEF_NONE);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttonPanier), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image30 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox13), image30, FALSE, FALSE, 0);

  label95 = gtk_label_new_with_mnemonic (_("Vos Reservation"));
  gtk_widget_show (label95);
  gtk_box_pack_start (GTK_BOX (hbox13), label95, FALSE, FALSE, 0);

  buttonCLocation = gtk_button_new_with_mnemonic (_("Location"));
  gtk_widget_show (buttonCLocation);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonCLocation, 488, 616);
  gtk_widget_set_size_request (buttonCLocation, 144, 49);

  buttonCHyber = gtk_button_new_with_mnemonic (_("Hybergement"));
  gtk_widget_show (buttonCHyber);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonCHyber, 760, 616);
  gtk_widget_set_size_request (buttonCHyber, 144, 49);

  g_signal_connect ((gpointer) buttondecoclient, "clicked",
                    G_CALLBACK (on_buttondecoclient_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonCVols, "clicked",
                    G_CALLBACK (on_buttonCVols_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonCLocation, "clicked",
                    G_CALLBACK (on_buttonCLocation_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonCHyber, "clicked",
                    G_CALLBACK (on_buttonCHyber_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ModeClient, ModeClient, "ModeClient");
  GLADE_HOOKUP_OBJECT (ModeClient, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (ModeClient, image21, "image21");
  GLADE_HOOKUP_OBJECT (ModeClient, label26, "label26");
  GLADE_HOOKUP_OBJECT (ModeClient, buttondecoclient, "buttondecoclient");
  GLADE_HOOKUP_OBJECT (ModeClient, buttonCVols, "buttonCVols");
  GLADE_HOOKUP_OBJECT (ModeClient, buttonPanier, "buttonPanier");
  GLADE_HOOKUP_OBJECT (ModeClient, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (ModeClient, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (ModeClient, image30, "image30");
  GLADE_HOOKUP_OBJECT (ModeClient, label95, "label95");
  GLADE_HOOKUP_OBJECT (ModeClient, buttonCLocation, "buttonCLocation");
  GLADE_HOOKUP_OBJECT (ModeClient, buttonCHyber, "buttonCHyber");

  return ModeClient;
}

GtkWidget*
create_Vols (void)
{
  GtkWidget *Vols;
  GtkWidget *fixed12;
  GtkWidget *image24;
  GtkWidget *comboboxentryDepartvol;
  GtkWidget *comboboxentryDestinationvol;
  GtkWidget *buttonvalidervol;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image25;
  GtkWidget *label92;
  GtkWidget *buttonretourVC;
  GtkWidget *image14;

  Vols = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Vols), _("Vols"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (Vols), fixed12);

  image24 = create_pixmap (Vols, "volclient.jpg");
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed12), image24, 0, 0);
  gtk_widget_set_size_request (image24, 1077, 805);

  comboboxentryDepartvol = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryDepartvol);
  gtk_fixed_put (GTK_FIXED (fixed12), comboboxentryDepartvol, 283, 235);
  gtk_widget_set_size_request (comboboxentryDepartvol, 206, 34);

  comboboxentryDestinationvol = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryDestinationvol);
  gtk_fixed_put (GTK_FIXED (fixed12), comboboxentryDestinationvol, 808, 235);
  gtk_widget_set_size_request (comboboxentryDestinationvol, 206, 34);

  buttonvalidervol = gtk_button_new ();
  gtk_widget_show (buttonvalidervol);
  gtk_fixed_put (GTK_FIXED (fixed12), buttonvalidervol, 808, 40);
  gtk_widget_set_size_request (buttonvalidervol, 152, 48);
  gtk_button_set_relief (GTK_BUTTON (buttonvalidervol), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (buttonvalidervol), FALSE);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonvalidervol), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image25 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox10), image25, FALSE, FALSE, 0);

  label92 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (hbox10), label92, FALSE, FALSE, 0);

  buttonretourVC = gtk_button_new ();
  gtk_widget_show (buttonretourVC);
  gtk_fixed_put (GTK_FIXED (fixed12), buttonretourVC, 88, 144);
  gtk_widget_set_size_request (buttonretourVC, 120, 48);

  image14 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_container_add (GTK_CONTAINER (buttonretourVC), image14);

  g_signal_connect ((gpointer) buttonvalidervol, "clicked",
                    G_CALLBACK (on_buttonvalidervol_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourVC, "clicked",
                    G_CALLBACK (on_buttonretourVC_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Vols, Vols, "Vols");
  GLADE_HOOKUP_OBJECT (Vols, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (Vols, image24, "image24");
  GLADE_HOOKUP_OBJECT (Vols, comboboxentryDepartvol, "comboboxentryDepartvol");
  GLADE_HOOKUP_OBJECT (Vols, comboboxentryDestinationvol, "comboboxentryDestinationvol");
  GLADE_HOOKUP_OBJECT (Vols, buttonvalidervol, "buttonvalidervol");
  GLADE_HOOKUP_OBJECT (Vols, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Vols, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Vols, image25, "image25");
  GLADE_HOOKUP_OBJECT (Vols, label92, "label92");
  GLADE_HOOKUP_OBJECT (Vols, buttonretourVC, "buttonretourVC");
  GLADE_HOOKUP_OBJECT (Vols, image14, "image14");

  return Vols;
}

GtkWidget*
create_Hybergement (void)
{
  GtkWidget *Hybergement;
  GtkWidget *fixed13;
  GtkWidget *image26;
  GtkWidget *comboboxentryHyberpays;
  GtkWidget *buttonvaliderhyber;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image27;
  GtkWidget *label93;
  GtkWidget *buttonretourHC;
  GtkWidget *image15;

  Hybergement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Hybergement), _("Hybergement"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (Hybergement), fixed13);

  image26 = create_pixmap (Hybergement, "heberclient.jpg");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed13), image26, 0, 0);
  gtk_widget_set_size_request (image26, 1040, 776);

  comboboxentryHyberpays = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryHyberpays);
  gtk_fixed_put (GTK_FIXED (fixed13), comboboxentryHyberpays, 208, 240);
  gtk_widget_set_size_request (comboboxentryHyberpays, 206, 34);

  buttonvaliderhyber = gtk_button_new ();
  gtk_widget_show (buttonvaliderhyber);
  gtk_fixed_put (GTK_FIXED (fixed13), buttonvaliderhyber, 777, 27);
  gtk_widget_set_size_request (buttonvaliderhyber, 152, 48);
  gtk_button_set_relief (GTK_BUTTON (buttonvaliderhyber), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (buttonvaliderhyber), FALSE);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttonvaliderhyber), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image27 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox11), image27, FALSE, FALSE, 0);

  label93 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label93);
  gtk_box_pack_start (GTK_BOX (hbox11), label93, FALSE, FALSE, 0);

  buttonretourHC = gtk_button_new ();
  gtk_widget_show (buttonretourHC);
  gtk_fixed_put (GTK_FIXED (fixed13), buttonretourHC, 88, 144);
  gtk_widget_set_size_request (buttonretourHC, 120, 48);

  image15 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_container_add (GTK_CONTAINER (buttonretourHC), image15);

  g_signal_connect ((gpointer) buttonvaliderhyber, "clicked",
                    G_CALLBACK (on_buttonvalidervol_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourHC, "clicked",
                    G_CALLBACK (on_buttonretourHC_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Hybergement, Hybergement, "Hybergement");
  GLADE_HOOKUP_OBJECT (Hybergement, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (Hybergement, image26, "image26");
  GLADE_HOOKUP_OBJECT (Hybergement, comboboxentryHyberpays, "comboboxentryHyberpays");
  GLADE_HOOKUP_OBJECT (Hybergement, buttonvaliderhyber, "buttonvaliderhyber");
  GLADE_HOOKUP_OBJECT (Hybergement, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Hybergement, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Hybergement, image27, "image27");
  GLADE_HOOKUP_OBJECT (Hybergement, label93, "label93");
  GLADE_HOOKUP_OBJECT (Hybergement, buttonretourHC, "buttonretourHC");
  GLADE_HOOKUP_OBJECT (Hybergement, image15, "image15");

  return Hybergement;
}

GtkWidget*
create_Location (void)
{
  GtkWidget *Location;
  GtkWidget *fixed14;
  GtkWidget *image28;
  GtkWidget *buttonvaliderlocation;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image29;
  GtkWidget *label94;
  GtkWidget *buttonretourLC;
  GtkWidget *image16;

  Location = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Location), _("Location"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (Location), fixed14);

  image28 = create_pixmap (Location, "locationclient.jpg");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed14), image28, 0, 0);
  gtk_widget_set_size_request (image28, 1080, 808);

  buttonvaliderlocation = gtk_button_new ();
  gtk_widget_show (buttonvaliderlocation);
  gtk_fixed_put (GTK_FIXED (fixed14), buttonvaliderlocation, 784, 40);
  gtk_widget_set_size_request (buttonvaliderlocation, 152, 48);
  gtk_button_set_relief (GTK_BUTTON (buttonvaliderlocation), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (buttonvaliderlocation), FALSE);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonvaliderlocation), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image29 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox12), image29, FALSE, FALSE, 0);

  label94 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label94);
  gtk_box_pack_start (GTK_BOX (hbox12), label94, FALSE, FALSE, 0);

  buttonretourLC = gtk_button_new ();
  gtk_widget_show (buttonretourLC);
  gtk_fixed_put (GTK_FIXED (fixed14), buttonretourLC, 88, 144);
  gtk_widget_set_size_request (buttonretourLC, 120, 48);

  image16 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_container_add (GTK_CONTAINER (buttonretourLC), image16);

  g_signal_connect ((gpointer) buttonvaliderlocation, "clicked",
                    G_CALLBACK (on_buttonvalidervol_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourLC, "clicked",
                    G_CALLBACK (on_buttonretourLC_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Location, Location, "Location");
  GLADE_HOOKUP_OBJECT (Location, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (Location, image28, "image28");
  GLADE_HOOKUP_OBJECT (Location, buttonvaliderlocation, "buttonvaliderlocation");
  GLADE_HOOKUP_OBJECT (Location, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Location, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Location, image29, "image29");
  GLADE_HOOKUP_OBJECT (Location, label94, "label94");
  GLADE_HOOKUP_OBJECT (Location, buttonretourLC, "buttonretourLC");
  GLADE_HOOKUP_OBJECT (Location, image16, "image16");

  return Location;
}

GtkWidget*
create_Inscription (void)
{
  GtkWidget *Inscription;
  GtkWidget *fixed15;
  GtkWidget *entryinscrinom;
  GtkWidget *entryinscriprenom;
  GtkWidget *entryinscricin;
  GtkWidget *entryinscriptionuser;
  GtkWidget *entryinscriptionpass;
  GtkWidget *image36;
  GtkWidget *buttonValiderinscri;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image17;
  GtkWidget *label81;
  GtkWidget *label82;
  GtkWidget *buttoninscriconnect;
  GtkWidget *label79;
  GtkWidget *label76;
  GtkWidget *label77;
  GtkWidget *label78;
  GtkWidget *label80;

  Inscription = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Inscription), _("Inscrivez-vous"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (Inscription), fixed15);

  entryinscrinom = gtk_entry_new ();
  gtk_widget_show (entryinscrinom);
  gtk_fixed_put (GTK_FIXED (fixed15), entryinscrinom, 408, 270);
  gtk_widget_set_size_request (entryinscrinom, 180, 36);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryinscrinom), 8226);

  entryinscriprenom = gtk_entry_new ();
  gtk_widget_show (entryinscriprenom);
  gtk_fixed_put (GTK_FIXED (fixed15), entryinscriprenom, 408, 311);
  gtk_widget_set_size_request (entryinscriprenom, 180, 36);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryinscriprenom), 8226);

  entryinscricin = gtk_entry_new ();
  gtk_widget_show (entryinscricin);
  gtk_fixed_put (GTK_FIXED (fixed15), entryinscricin, 408, 353);
  gtk_widget_set_size_request (entryinscricin, 180, 36);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryinscricin), 8226);

  entryinscriptionuser = gtk_entry_new ();
  gtk_widget_show (entryinscriptionuser);
  gtk_fixed_put (GTK_FIXED (fixed15), entryinscriptionuser, 408, 396);
  gtk_widget_set_size_request (entryinscriptionuser, 180, 36);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryinscriptionuser), 8226);

  entryinscriptionpass = gtk_entry_new ();
  gtk_widget_show (entryinscriptionpass);
  gtk_fixed_put (GTK_FIXED (fixed15), entryinscriptionpass, 408, 439);
  gtk_widget_set_size_request (entryinscriptionpass, 180, 36);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryinscriptionpass), 8226);

  image36 = create_pixmap (Inscription, "inscri.jpg");
  gtk_widget_show (image36);
  gtk_fixed_put (GTK_FIXED (fixed15), image36, 0, 0);
  gtk_widget_set_size_request (image36, 1008, 749);

  buttonValiderinscri = gtk_button_new ();
  gtk_widget_show (buttonValiderinscri);
  gtk_fixed_put (GTK_FIXED (fixed15), buttonValiderinscri, 560, 488);
  gtk_widget_set_size_request (buttonValiderinscri, 144, 41);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonValiderinscri), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image17 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox8), image17, FALSE, FALSE, 0);

  label81 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label81);
  gtk_box_pack_start (GTK_BOX (hbox8), label81, FALSE, FALSE, 0);

  label82 = gtk_label_new (_("Si vous avez d\303\251j\303\240 un compte \n                                             Connectez vous "));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed15), label82, 344, 656);
  gtk_widget_set_size_request (label82, 416, 48);

  buttoninscriconnect = gtk_button_new_with_mnemonic (_("Connecter"));
  gtk_widget_show (buttoninscriconnect);
  gtk_fixed_put (GTK_FIXED (fixed15), buttoninscriconnect, 771, 656);
  gtk_widget_set_size_request (buttoninscriconnect, 170, 48);

  label79 = gtk_label_new (_("User      :"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed15), label79, 312, 399);
  gtk_widget_set_size_request (label79, 88, 32);

  label76 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed15), label76, 320, 272);
  gtk_widget_set_size_request (label76, 88, 32);

  label77 = gtk_label_new (_("Pr\303\251nom  : "));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed15), label77, 307, 314);
  gtk_widget_set_size_request (label77, 88, 32);

  label78 = gtk_label_new (_("CIN        : "));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed15), label78, 312, 356);
  gtk_widget_set_size_request (label78, 88, 32);

  label80 = gtk_label_new (_("Password :"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed15), label80, 301, 441);
  gtk_widget_set_size_request (label80, 88, 32);

  g_signal_connect ((gpointer) buttonValiderinscri, "clicked",
                    G_CALLBACK (on_buttonValiderinscri_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttoninscriconnect, "clicked",
                    G_CALLBACK (on_buttoninscriconnect_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Inscription, Inscription, "Inscription");
  GLADE_HOOKUP_OBJECT (Inscription, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (Inscription, entryinscrinom, "entryinscrinom");
  GLADE_HOOKUP_OBJECT (Inscription, entryinscriprenom, "entryinscriprenom");
  GLADE_HOOKUP_OBJECT (Inscription, entryinscricin, "entryinscricin");
  GLADE_HOOKUP_OBJECT (Inscription, entryinscriptionuser, "entryinscriptionuser");
  GLADE_HOOKUP_OBJECT (Inscription, entryinscriptionpass, "entryinscriptionpass");
  GLADE_HOOKUP_OBJECT (Inscription, image36, "image36");
  GLADE_HOOKUP_OBJECT (Inscription, buttonValiderinscri, "buttonValiderinscri");
  GLADE_HOOKUP_OBJECT (Inscription, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Inscription, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Inscription, image17, "image17");
  GLADE_HOOKUP_OBJECT (Inscription, label81, "label81");
  GLADE_HOOKUP_OBJECT (Inscription, label82, "label82");
  GLADE_HOOKUP_OBJECT (Inscription, buttoninscriconnect, "buttoninscriconnect");
  GLADE_HOOKUP_OBJECT (Inscription, label79, "label79");
  GLADE_HOOKUP_OBJECT (Inscription, label76, "label76");
  GLADE_HOOKUP_OBJECT (Inscription, label77, "label77");
  GLADE_HOOKUP_OBJECT (Inscription, label78, "label78");
  GLADE_HOOKUP_OBJECT (Inscription, label80, "label80");

  return Inscription;
}

GtkWidget*
create_ajouteremp (void)
{
  GtkWidget *ajouteremp;
  GtkWidget *fixed16;
  GtkWidget *entrynomemp;
  GtkWidget *entryprenomemp;
  GtkWidget *entryuseremp;
  GtkWidget *entrypassemp;
  GtkWidget *label83;
  GtkWidget *label84;
  GtkWidget *label87;
  GtkWidget *label86;
  GtkWidget *label85;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *year_adj;
  GtkWidget *year;
  GtkWidget *label88;
  GtkWidget *label89;
  GtkWidget *label90;
  GtkWidget *buttonretourajoutadmin;
  GtkWidget *image23;
  GtkWidget *buttonvaliderajouteremploye;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image22;
  GtkWidget *label91;

  ajouteremp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouteremp), _("Ajouter Employee"));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (ajouteremp), fixed16);

  entrynomemp = gtk_entry_new ();
  gtk_widget_show (entrynomemp);
  gtk_fixed_put (GTK_FIXED (fixed16), entrynomemp, 280, 64);
  gtk_widget_set_size_request (entrynomemp, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynomemp), 8226);

  entryprenomemp = gtk_entry_new ();
  gtk_widget_show (entryprenomemp);
  gtk_fixed_put (GTK_FIXED (fixed16), entryprenomemp, 280, 104);
  gtk_widget_set_size_request (entryprenomemp, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenomemp), 8226);

  entryuseremp = gtk_entry_new ();
  gtk_widget_show (entryuseremp);
  gtk_fixed_put (GTK_FIXED (fixed16), entryuseremp, 280, 304);
  gtk_widget_set_size_request (entryuseremp, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryuseremp), 8226);

  entrypassemp = gtk_entry_new ();
  gtk_widget_show (entrypassemp);
  gtk_fixed_put (GTK_FIXED (fixed16), entrypassemp, 280, 344);
  gtk_widget_set_size_request (entrypassemp, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrypassemp), 8226);

  label83 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed16), label83, 184, 64);
  gtk_widget_set_size_request (label83, 80, 32);

  label84 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed16), label84, 168, 104);
  gtk_widget_set_size_request (label84, 88, 32);

  label87 = gtk_label_new (_("Password :"));
  gtk_widget_show (label87);
  gtk_fixed_put (GTK_FIXED (fixed16), label87, 160, 344);
  gtk_widget_set_size_request (label87, 104, 32);

  label86 = gtk_label_new (_("user :"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed16), label86, 184, 304);
  gtk_widget_set_size_request (label86, 96, 32);

  label85 = gtk_label_new (_("Date de Recrutement  :"));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed16), label85, 64, 200);
  gtk_widget_set_size_request (label85, 176, 32);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed16), jour, 304, 200);
  gtk_widget_set_size_request (jour, 70, 34);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed16), mois, 440, 200);
  gtk_widget_set_size_request (mois, 70, 34);

  year_adj = gtk_adjustment_new (1, 2000, 2200, 1, 10, 10);
  year = gtk_spin_button_new (GTK_ADJUSTMENT (year_adj), 1, 0);
  gtk_widget_show (year);
  gtk_fixed_put (GTK_FIXED (fixed16), year, 600, 200);
  gtk_widget_set_size_request (year, 70, 34);

  label88 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed16), label88, 248, 208);
  gtk_widget_set_size_request (label88, 56, 24);

  label89 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed16), label89, 376, 208);
  gtk_widget_set_size_request (label89, 56, 24);

  label90 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed16), label90, 528, 208);
  gtk_widget_set_size_request (label90, 56, 24);

  buttonretourajoutadmin = gtk_button_new ();
  gtk_widget_show (buttonretourajoutadmin);
  gtk_fixed_put (GTK_FIXED (fixed16), buttonretourajoutadmin, 8, 8);
  gtk_widget_set_size_request (buttonretourajoutadmin, 88, 32);

  image23 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_container_add (GTK_CONTAINER (buttonretourajoutadmin), image23);

  buttonvaliderajouteremploye = gtk_button_new ();
  gtk_widget_show (buttonvaliderajouteremploye);
  gtk_fixed_put (GTK_FIXED (fixed16), buttonvaliderajouteremploye, 488, 424);
  gtk_widget_set_size_request (buttonvaliderajouteremploye, 160, 41);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonvaliderajouteremploye), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image22 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox9), image22, FALSE, FALSE, 0);

  label91 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (hbox9), label91, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonretourajoutadmin, "clicked",
                    G_CALLBACK (on_buttonretourajoutadmin_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonvaliderajouteremploye, "clicked",
                    G_CALLBACK (on_buttonvaliderajouteremploye_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouteremp, ajouteremp, "ajouteremp");
  GLADE_HOOKUP_OBJECT (ajouteremp, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (ajouteremp, entrynomemp, "entrynomemp");
  GLADE_HOOKUP_OBJECT (ajouteremp, entryprenomemp, "entryprenomemp");
  GLADE_HOOKUP_OBJECT (ajouteremp, entryuseremp, "entryuseremp");
  GLADE_HOOKUP_OBJECT (ajouteremp, entrypassemp, "entrypassemp");
  GLADE_HOOKUP_OBJECT (ajouteremp, label83, "label83");
  GLADE_HOOKUP_OBJECT (ajouteremp, label84, "label84");
  GLADE_HOOKUP_OBJECT (ajouteremp, label87, "label87");
  GLADE_HOOKUP_OBJECT (ajouteremp, label86, "label86");
  GLADE_HOOKUP_OBJECT (ajouteremp, label85, "label85");
  GLADE_HOOKUP_OBJECT (ajouteremp, jour, "jour");
  GLADE_HOOKUP_OBJECT (ajouteremp, mois, "mois");
  GLADE_HOOKUP_OBJECT (ajouteremp, year, "year");
  GLADE_HOOKUP_OBJECT (ajouteremp, label88, "label88");
  GLADE_HOOKUP_OBJECT (ajouteremp, label89, "label89");
  GLADE_HOOKUP_OBJECT (ajouteremp, label90, "label90");
  GLADE_HOOKUP_OBJECT (ajouteremp, buttonretourajoutadmin, "buttonretourajoutadmin");
  GLADE_HOOKUP_OBJECT (ajouteremp, image23, "image23");
  GLADE_HOOKUP_OBJECT (ajouteremp, buttonvaliderajouteremploye, "buttonvaliderajouteremploye");
  GLADE_HOOKUP_OBJECT (ajouteremp, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (ajouteremp, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (ajouteremp, image22, "image22");
  GLADE_HOOKUP_OBJECT (ajouteremp, label91, "label91");

  return ajouteremp;
}

GtkWidget*
create_VolsE (void)
{
  GtkWidget *VolsE;
  GtkWidget *fixed17;
  GtkWidget *image37;
  GtkWidget *buttonretourVP;
  GtkWidget *image40;

  VolsE = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (VolsE), _("Vols"));

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (VolsE), fixed17);

  image37 = create_pixmap (VolsE, "volsemp.jpg");
  gtk_widget_show (image37);
  gtk_fixed_put (GTK_FIXED (fixed17), image37, 0, 0);
  gtk_widget_set_size_request (image37, 1080, 808);

  buttonretourVP = gtk_button_new ();
  gtk_widget_show (buttonretourVP);
  gtk_fixed_put (GTK_FIXED (fixed17), buttonretourVP, 128, 104);
  gtk_widget_set_size_request (buttonretourVP, 120, 48);

  image40 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_container_add (GTK_CONTAINER (buttonretourVP), image40);

  g_signal_connect ((gpointer) buttonretourVP, "clicked",
                    G_CALLBACK (on_buttonretourVP_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (VolsE, VolsE, "VolsE");
  GLADE_HOOKUP_OBJECT (VolsE, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (VolsE, image37, "image37");
  GLADE_HOOKUP_OBJECT (VolsE, buttonretourVP, "buttonretourVP");
  GLADE_HOOKUP_OBJECT (VolsE, image40, "image40");

  return VolsE;
}

GtkWidget*
create_HybergementE (void)
{
  GtkWidget *HybergementE;
  GtkWidget *fixed18;
  GtkWidget *image38;
  GtkWidget *buttonretourHP;
  GtkWidget *image41;

  HybergementE = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (HybergementE), _("Hybergement"));

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (HybergementE), fixed18);

  image38 = create_pixmap (HybergementE, "hyberemp.jpg");
  gtk_widget_show (image38);
  gtk_fixed_put (GTK_FIXED (fixed18), image38, 0, 0);
  gtk_widget_set_size_request (image38, 1080, 808);

  buttonretourHP = gtk_button_new ();
  gtk_widget_show (buttonretourHP);
  gtk_fixed_put (GTK_FIXED (fixed18), buttonretourHP, 112, 120);
  gtk_widget_set_size_request (buttonretourHP, 120, 48);

  image41 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image41);
  gtk_container_add (GTK_CONTAINER (buttonretourHP), image41);

  g_signal_connect ((gpointer) buttonretourHP, "clicked",
                    G_CALLBACK (on_buttonretourHP_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (HybergementE, HybergementE, "HybergementE");
  GLADE_HOOKUP_OBJECT (HybergementE, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (HybergementE, image38, "image38");
  GLADE_HOOKUP_OBJECT (HybergementE, buttonretourHP, "buttonretourHP");
  GLADE_HOOKUP_OBJECT (HybergementE, image41, "image41");

  return HybergementE;
}

GtkWidget*
create_LocationE (void)
{
  GtkWidget *LocationE;
  GtkWidget *fixed19;
  GtkWidget *image39;
  GtkWidget *buttonretourLP;
  GtkWidget *image42;

  LocationE = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (LocationE), _("Location"));

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (LocationE), fixed19);

  image39 = create_pixmap (LocationE, "locemp.jpg");
  gtk_widget_show (image39);
  gtk_fixed_put (GTK_FIXED (fixed19), image39, 0, 0);
  gtk_widget_set_size_request (image39, 1080, 816);

  buttonretourLP = gtk_button_new ();
  gtk_widget_show (buttonretourLP);
  gtk_fixed_put (GTK_FIXED (fixed19), buttonretourLP, 128, 112);
  gtk_widget_set_size_request (buttonretourLP, 120, 48);

  image42 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image42);
  gtk_container_add (GTK_CONTAINER (buttonretourLP), image42);

  g_signal_connect ((gpointer) buttonretourLP, "clicked",
                    G_CALLBACK (on_buttonretourLP_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (LocationE, LocationE, "LocationE");
  GLADE_HOOKUP_OBJECT (LocationE, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (LocationE, image39, "image39");
  GLADE_HOOKUP_OBJECT (LocationE, buttonretourLP, "buttonretourLP");
  GLADE_HOOKUP_OBJECT (LocationE, image42, "image42");

  return LocationE;
}

