/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Home (void);
GtkWidget* create_ModeVisiteur (void);
GtkWidget* create_ModeAdmin (void);
GtkWidget* create_GestionAClient (void);
GtkWidget* create_GestionAEmployes (void);
GtkWidget* create_ModeEmploye (void);
GtkWidget* create_GestionEClient (void);
GtkWidget* create_Prestations (void);
GtkWidget* create_Factures (void);
GtkWidget* create_ModeClient (void);
GtkWidget* create_Vols (void);
GtkWidget* create_Hybergement (void);
GtkWidget* create_Location (void);
GtkWidget* create_Inscription (void);
GtkWidget* create_ajouteremp (void);
GtkWidget* create_VolsE (void);
GtkWidget* create_HybergementE (void);
GtkWidget* create_LocationE (void);
GtkWidget* create_message (void);
GtkWidget* create_reclamation (void);
GtkWidget* create_contacter (void);
GtkWidget* create_reclamer (void);
GtkWidget* create_messageE (void);
GtkWidget* create_reclamationE (void);
GtkWidget* create_Volsvisiteur (void);
GtkWidget* create_Hybergementvisiteur (void);
GtkWidget* create_Locationvisiteur (void);
GtkWidget* create_ajoutervol (void);
