/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Home (void);
GtkWidget* create_ModeVisiteur (void);
GtkWidget* create_ModeAdmin (void);
GtkWidget* create_GestionAClient (void);
GtkWidget* create_GestionAEmployes (void);
GtkWidget* create_ModeEmploye (void);
GtkWidget* create_GestionEClient (void);
GtkWidget* create_Prestations (void);
GtkWidget* create_Factures (void);
GtkWidget* create_ModeClient (void);
GtkWidget* create_Vols (void);
GtkWidget* create_Hybergement (void);
GtkWidget* create_Location (void);
GtkWidget* create_Inscription (void);
