/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Home;
  //GtkWidget *ModeVisiteur;
  //GtkWidget *ModeAdmin;
  /*GtkWidget *GestionAClient;
  GtkWidget *GestionAEmployes;
  GtkWidget *ModeEmploye;
  GtkWidget *GestionEClient;
  GtkWidget *Prestations;
  GtkWidget *Factures;
  GtkWidget *ModeClient;
  GtkWidget *Vols;
  GtkWidget *Hybergement;
  GtkWidget *Location;*/

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Home = create_Home ();
  gtk_widget_show (Home);
  //ModeVisiteur = create_ModeVisiteur ();
  //gtk_widget_show (ModeVisiteur);
  //ModeAdmin = create_ModeAdmin ();
  //gtk_widget_show (ModeAdmin);
  /*GestionAClient = create_GestionAClient ();
  gtk_widget_show (GestionAClient);
  GestionAEmployes = create_GestionAEmployes ();
  gtk_widget_show (GestionAEmployes);
  ModeEmploye = create_ModeEmploye ();
  gtk_widget_show (ModeEmploye);
  GestionEClient = create_GestionEClient ();
  gtk_widget_show (GestionEClient);
  Prestations = create_Prestations ();
  gtk_widget_show (Prestations);
  Factures = create_Factures ();
  gtk_widget_show (Factures);
  ModeClient = create_ModeClient ();
  gtk_widget_show (ModeClient);
  Vols = create_Vols ();
  gtk_widget_show (Vols);
  Hybergement = create_Hybergement ();
  gtk_widget_show (Hybergement);
  Location = create_Location ();
  gtk_widget_show (Location);*/

  gtk_main ();
  return 0;
}

